<?php

namespace AppBundle\Repository;

/**
 * AccessConcurrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessConcurrentRepository extends \Doctrine\ORM\EntityRepository
{
    // -----------------------------------------------------------------------------------------------------------------

    /**
     * @return ArrayCollection
     */
    function getAccessToDelete()
    {
        $date = new \DateTime();

        $query = $this->createQueryBuilder('access')
            ->where('access.date < :now ')
            ->setParameter('now', $date->modify('-10 minutes'))
            ->getQuery()
        
        ;

        return $query->getResult();
    }
}
