<?php

namespace AppBundle\Repository;

/**
 * HabilitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabilitationRepository extends \Doctrine\ORM\EntityRepository
{
}
