<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProfessionnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionnelRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste paginée des professionnels
     * @param $page
     * @param $nbPerPage
     * @return Paginator
     */
    public function getPaginatedProfessionnels($page, $nbPerPage, $search)
    {


        $query = $this->createQueryBuilder('professionnel')
            ->leftJoin('professionnel.profil', 'profil')
            ->addSelect('profil')

            ->leftJoin('professionnel.statut', 'statut')
            ->addSelect('statut')

            ->leftJoin('professionnel.statutProfessionnel', 'statutProfessionnel')
            ->addSelect('statutProfessionnel')

            ->leftJoin('professionnel.access', 'access')
            ->addSelect('access')

            ->leftJoin('professionnel.titre', 'titre')
            ->addSelect('titre')

            ->leftJoin('professionnel.titreComplement', 'titreComplement')
            ->addSelect('titreComplement')
            ;

        if($search['nom'] != ''){
            $query = $query->andWhere('professionnel.nom  LIKE :nom')
                ->setParameter('nom', '%'.$search['nom'].'%');
        }
        
        if($search['profil'] != ''){
            $query = $query->andWhere('profil.id  = :profil_id')
                ->setParameter('profil_id', $search['profil']);
        }

        if($search['statut'] != ''){
            $query = $query->andWhere('statut.id  = :statut_id')
                ->setParameter('statut_id', $search['statut']);
        }

        if($search['titreComplement'] != ''){
            $query = $query->andWhere('titreComplement.id  = :titreComplement_id')
                ->setParameter('titreComplement_id', $search['titreComplement']);
        }

        if($search['titreComplementAutres'] != ''){
            $query = $query->andWhere('titreComplement.id  = :titreComplementAutres_id')
                ->setParameter('titreComplementAutres_id', $search['titreComplementAutres']);
        }

        if($search['statutProfessionnel'] != ''){
            $query = $query->andWhere('statutProfessionnel.id  = :statutProfessionnel_id')
                ->setParameter('statutProfessionnel_id', $search['statutProfessionnel']);
        }

        if($search['disponibilite'] != ''){
            $query = $query->andWhere('professionnel.disponibilite  = :disponibilite')
                ->setParameter('disponibilite', $search['disponibilite']);
        }

        if($search['dateDebut'] != ''){
            $query = $query->andWhere('professionnel.dateCreation >= :dateDebut')
                ->setParameter('dateDebut', $search['dateDebut']);
        }

        if($search['dateFin'] != ''){
            $query = $query->andWhere('professionnel.dateCreation <= :dateFin')
                ->setParameter('dateFin', $search['dateFin']);
        }

        if($search['formationInitiale'] != ''){
            $query = $query->andWhere('professionnel.formationInitiale = :formationInitiale')
                ->setParameter('formationInitiale', $search['formationInitiale']);
        }

        $hour = sprintf('%02d', $search['heure']['hour']).':'.sprintf('%02d', $search['heure']['minute']);
        if($hour != '00:00'){
            $query = $query->andWhere('professionnel.heure = :heure')
                ->setParameter('heure', $search['heure']['hour'].':'.$search['heure']['minute']);
        }


        $query
            ->orderBy('professionnel.id', 'DESC')
            ->setFirstResult(($page - 1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
            ->getQuery()
        ;

        return new Paginator($query, false);
    }

    /**
     * Liste des professionnels
     * @param $page
     * @param $nbPerPage
     * @return Paginator
     */
    public function getListeActuelle($search)
    {
        

        $query = $this->createQueryBuilder('professionnel')
            ->leftJoin('professionnel.profil', 'profil')
            ->addSelect('profil')

            ->leftJoin('professionnel.statut', 'statut')
            ->addSelect('statut')

            ->leftJoin('professionnel.statutProfessionnel', 'statutProfessionnel')
            ->addSelect('statutProfessionnel')

            ->leftJoin('professionnel.access', 'access')
            ->addSelect('access')

            ->leftJoin('professionnel.titre', 'titre')
            ->addSelect('titre')

            ->leftJoin('professionnel.titreComplement', 'titreComplement')
            ->addSelect('titreComplement')
        ;


        if($search['nom'] != ''){
            $query = $query->andWhere('professionnel.nom  LIKE :nom')
                ->setParameter('nom', '%'.$search['nom'].'%');
        }

        if($search['profil'] != ''){
            $query = $query->andWhere('profil.id  = :profil_id')
                ->setParameter('profil_id', $search['profil']);
        }

        if($search['statut'] != ''){
            $query = $query->andWhere('statut.id  = :statut_id')
                ->setParameter('statut_id', $search['statut']);
        }

        if($search['statutProfessionnel'] != ''){
            $query = $query->andWhere('statutProfessionnel.id  = :statutProfessionnel_id')
                ->setParameter('statutProfessionnel_id', $search['statutProfessionnel']);
        }

        if($search['disponibilite'] != ''){
            $query = $query->andWhere('professionnel.disponibilite  = :disponibilite')
                ->setParameter('disponibilite', $search['disponibilite']);
        }

        if($search['dateDebut'] != ''){
            $query = $query->andWhere('professionnel.dateCreation >= :dateDebut')
                ->setParameter('dateDebut', $search['dateDebut']);
        }

        if($search['dateFin'] != ''){
            $query = $query->andWhere('professionnel.dateCreation <= :dateFin')
                ->setParameter('dateFin', $search['dateFin']);
        }

        if($search['formationInitiale'] != ''){
            $query = $query->andWhere('professionnel.formationInitiale = :formationInitiale')
                ->setParameter('formationInitiale', $search['formationInitiale']);
        }

        $hour = sprintf('%02d', $search['heure']['hour']).':'.sprintf('%02d', $search['heure']['minute']);
        if($hour != '00:00'){
            $query = $query->andWhere('professionnel.heure = :heure')
                ->setParameter('heure', $search['heure']['hour'].':'.$search['heure']['minute']);
        }


        $query
            ->orderBy('professionnel.id', 'DESC')
            ->getQuery()
        ;

        return new Paginator($query, false);
    }

}
