<?php

namespace AppBundle\Repository;

/**
 * StatutProfessionnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutProfessionnelRepository extends \Doctrine\ORM\EntityRepository
{
}
