<?php

namespace AppBundle\Repository;

/**
 * TitreComplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitreComplementRepository extends \Doctrine\ORM\EntityRepository
{
}
