<?php

namespace AppBundle\Repository;

/**
 * TitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitreRepository extends \Doctrine\ORM\EntityRepository
{
}
