imports:
    - { resource: config.yml }
    - { resource: parameters.yml }
    - { resource: params.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: true
    profiler: false