# Parameters
parameters:

    locale: fr
    cle_captcha: 6LfIPrIUAAAAADZSW9Wc-OYa43iuVNysE7rRbOIJ

    mailer_from_name: Extranet ACT4HER
    mailer_from: act4her@test.com
    mailer_inscription: test@test.com
    mailer_cc: test@test.com

    directory: "%kernel.root_dir%/../src/AppBundle/Resources/documents/"

    site:
        name: ACT4HER
        type: accompagnement