# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
services:
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true